=begin
#MockServer API

#MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

The version of the OpenAPI document: 5.13.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'cgi'

module MockServer
  class ExpectationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # create expectation
    # @param expectations [Expectations] expectation(s) to create
    # @param [Hash] opts the optional parameters
    # @return [Array<Expectation>]
    def mockserver_expectation_put(expectations, opts = {})
      data, _status_code, _headers = mockserver_expectation_put_with_http_info(expectations, opts)
      data
    end

    # create expectation
    # @param expectations [Expectations] expectation(s) to create
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Expectation>, Integer, Hash)>] Array<Expectation> data, response status code and response headers
    def mockserver_expectation_put_with_http_info(expectations, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ExpectationApi.mockserver_expectation_put ...'
      end
      # resource path
      local_var_path = '/mockserver/expectation'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(expectations)

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Expectation>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"ExpectationApi.mockserver_expectation_put",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ExpectationApi#mockserver_expectation_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # create expectations from OpenAPI or Swagger
    # @param open_api_expectations [OpenAPIExpectations] expectation(s) to create
    # @param [Hash] opts the optional parameters
    # @return [Array<Expectation>]
    def mockserver_openapi_put(open_api_expectations, opts = {})
      data, _status_code, _headers = mockserver_openapi_put_with_http_info(open_api_expectations, opts)
      data
    end

    # create expectations from OpenAPI or Swagger
    # @param open_api_expectations [OpenAPIExpectations] expectation(s) to create
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Expectation>, Integer, Hash)>] Array<Expectation> data, response status code and response headers
    def mockserver_openapi_put_with_http_info(open_api_expectations, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ExpectationApi.mockserver_openapi_put ...'
      end
      # verify the required parameter 'open_api_expectations' is set
      if @api_client.config.client_side_validation && open_api_expectations.nil?
        fail ArgumentError, "Missing the required parameter 'open_api_expectations' when calling ExpectationApi.mockserver_openapi_put"
      end
      # resource path
      local_var_path = '/mockserver/openapi'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(open_api_expectations)

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Expectation>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"ExpectationApi.mockserver_openapi_put",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ExpectationApi#mockserver_openapi_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
