=begin
#MockServer API

#MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

The version of the OpenAPI document: 5.13.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'mockserver-client/api_client'
require 'mockserver-client/api_error'
require 'mockserver-client/version'
require 'mockserver-client/configuration'

# Models
require 'mockserver-client/models/body'
require 'mockserver-client/models/body_any_of'
require 'mockserver-client/models/body_any_of1'
require 'mockserver-client/models/body_any_of2'
require 'mockserver-client/models/body_any_of3'
require 'mockserver-client/models/body_any_of4'
require 'mockserver-client/models/body_any_of5'
require 'mockserver-client/models/body_any_of6'
require 'mockserver-client/models/body_any_of7'
require 'mockserver-client/models/body_any_of8'
require 'mockserver-client/models/body_any_of9'
require 'mockserver-client/models/body_with_content_type'
require 'mockserver-client/models/body_with_content_type_any_of'
require 'mockserver-client/models/body_with_content_type_any_of1'
require 'mockserver-client/models/body_with_content_type_any_of2'
require 'mockserver-client/models/body_with_content_type_any_of3'
require 'mockserver-client/models/connection_options'
require 'mockserver-client/models/delay'
require 'mockserver-client/models/expectation'
require 'mockserver-client/models/expectation_id'
require 'mockserver-client/models/expectations'
require 'mockserver-client/models/http_class_callback'
require 'mockserver-client/models/http_error'
require 'mockserver-client/models/http_forward'
require 'mockserver-client/models/http_object_callback'
require 'mockserver-client/models/http_override_forwarded_request'
require 'mockserver-client/models/http_override_forwarded_request_one_of'
require 'mockserver-client/models/http_override_forwarded_request_one_of1'
require 'mockserver-client/models/http_override_forwarded_request_one_of_request_modifier'
require 'mockserver-client/models/http_override_forwarded_request_one_of_request_modifier_cookies'
require 'mockserver-client/models/http_override_forwarded_request_one_of_request_modifier_path'
require 'mockserver-client/models/http_override_forwarded_request_one_of_request_modifier_query_string_parameters'
require 'mockserver-client/models/http_override_forwarded_request_one_of_response_modifier'
require 'mockserver-client/models/http_request'
require 'mockserver-client/models/http_response'
require 'mockserver-client/models/http_template'
require 'mockserver-client/models/key_to_multi_value'
require 'mockserver-client/models/key_to_multi_value_one_of'
require 'mockserver-client/models/key_to_value'
require 'mockserver-client/models/open_api_definition'
require 'mockserver-client/models/open_api_expectation'
require 'mockserver-client/models/open_api_expectations'
require 'mockserver-client/models/ports'
require 'mockserver-client/models/positive_integer_default0'
require 'mockserver-client/models/request_definition'
require 'mockserver-client/models/schema'
require 'mockserver-client/models/socket_address'
require 'mockserver-client/models/string_or_json_schema'
require 'mockserver-client/models/string_or_json_schema_one_of'
require 'mockserver-client/models/time_to_live'
require 'mockserver-client/models/times'
require 'mockserver-client/models/verification'
require 'mockserver-client/models/verification_sequence'
require 'mockserver-client/models/verification_times'

# APIs
require 'mockserver-client/api/control_api'
require 'mockserver-client/api/expectation_api'
require 'mockserver-client/api/verify_api'

module MockServer
  class << self
    # Customize default settings for the SDK using block.
    #   MockServer.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
