=begin
#MockServer API

#MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

The version of the OpenAPI document: 5.13.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module MockServer
  # Core schema meta-schema
  class Schema
    attr_accessor :id

    attr_accessor :schema

    attr_accessor :title

    attr_accessor :description

    attr_accessor :default

    attr_accessor :multiple_of

    attr_accessor :maximum

    attr_accessor :exclusive_maximum

    attr_accessor :minimum

    attr_accessor :exclusive_minimum

    attr_accessor :max_length

    attr_accessor :min_length

    attr_accessor :pattern

    attr_accessor :additional_items

    attr_accessor :items

    attr_accessor :max_items

    attr_accessor :min_items

    attr_accessor :unique_items

    attr_accessor :max_properties

    attr_accessor :min_properties

    attr_accessor :required

    attr_accessor :additional_properties

    attr_accessor :definitions

    attr_accessor :properties

    attr_accessor :pattern_properties

    attr_accessor :dependencies

    attr_accessor :enum

    attr_accessor :type

    attr_accessor :format

    attr_accessor :all_of

    attr_accessor :any_of

    attr_accessor :one_of

    attr_accessor :_not

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'schema' => :'$schema',
        :'title' => :'title',
        :'description' => :'description',
        :'default' => :'default',
        :'multiple_of' => :'multipleOf',
        :'maximum' => :'maximum',
        :'exclusive_maximum' => :'exclusiveMaximum',
        :'minimum' => :'minimum',
        :'exclusive_minimum' => :'exclusiveMinimum',
        :'max_length' => :'maxLength',
        :'min_length' => :'minLength',
        :'pattern' => :'pattern',
        :'additional_items' => :'additionalItems',
        :'items' => :'items',
        :'max_items' => :'maxItems',
        :'min_items' => :'minItems',
        :'unique_items' => :'uniqueItems',
        :'max_properties' => :'maxProperties',
        :'min_properties' => :'minProperties',
        :'required' => :'required',
        :'additional_properties' => :'additionalProperties',
        :'definitions' => :'definitions',
        :'properties' => :'properties',
        :'pattern_properties' => :'patternProperties',
        :'dependencies' => :'dependencies',
        :'enum' => :'enum',
        :'type' => :'type',
        :'format' => :'format',
        :'all_of' => :'allOf',
        :'any_of' => :'anyOf',
        :'one_of' => :'oneOf',
        :'_not' => :'not'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'schema' => :'String',
        :'title' => :'String',
        :'description' => :'String',
        :'default' => :'Object',
        :'multiple_of' => :'Float',
        :'maximum' => :'Float',
        :'exclusive_maximum' => :'Boolean',
        :'minimum' => :'Float',
        :'exclusive_minimum' => :'Boolean',
        :'max_length' => :'Integer',
        :'min_length' => :'PositiveIntegerDefault0',
        :'pattern' => :'String',
        :'additional_items' => :'AnyOfboolean',
        :'items' => :'AnyOfschemaArray',
        :'max_items' => :'Integer',
        :'min_items' => :'PositiveIntegerDefault0',
        :'unique_items' => :'Boolean',
        :'max_properties' => :'Integer',
        :'min_properties' => :'PositiveIntegerDefault0',
        :'required' => :'StringArray',
        :'additional_properties' => :'AnyOfboolean',
        :'definitions' => :'Hash<String, >',
        :'properties' => :'Hash<String, >',
        :'pattern_properties' => :'Hash<String, >',
        :'dependencies' => :'Hash<String, AnyOfstringArray>',
        :'enum' => :'Array<NULL_SCHEMA_ERR>',
        :'type' => :'AnyOfsimpleTypesset',
        :'format' => :'String',
        :'all_of' => :'SchemaArray',
        :'any_of' => :'SchemaArray',
        :'one_of' => :'SchemaArray',
        :'_not' => :''
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'additional_items',
        :'items',
        :'additional_properties',
        :'type',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MockServer::Schema` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MockServer::Schema`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'schema')
        self.schema = attributes[:'schema']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'default')
        self.default = attributes[:'default']
      end

      if attributes.key?(:'multiple_of')
        self.multiple_of = attributes[:'multiple_of']
      end

      if attributes.key?(:'maximum')
        self.maximum = attributes[:'maximum']
      end

      if attributes.key?(:'exclusive_maximum')
        self.exclusive_maximum = attributes[:'exclusive_maximum']
      else
        self.exclusive_maximum = false
      end

      if attributes.key?(:'minimum')
        self.minimum = attributes[:'minimum']
      end

      if attributes.key?(:'exclusive_minimum')
        self.exclusive_minimum = attributes[:'exclusive_minimum']
      else
        self.exclusive_minimum = false
      end

      if attributes.key?(:'max_length')
        self.max_length = attributes[:'max_length']
      end

      if attributes.key?(:'min_length')
        self.min_length = attributes[:'min_length']
      end

      if attributes.key?(:'pattern')
        self.pattern = attributes[:'pattern']
      end

      if attributes.key?(:'additional_items')
        self.additional_items = attributes[:'additional_items']
      end

      if attributes.key?(:'items')
        self.items = attributes[:'items']
      end

      if attributes.key?(:'max_items')
        self.max_items = attributes[:'max_items']
      end

      if attributes.key?(:'min_items')
        self.min_items = attributes[:'min_items']
      end

      if attributes.key?(:'unique_items')
        self.unique_items = attributes[:'unique_items']
      else
        self.unique_items = false
      end

      if attributes.key?(:'max_properties')
        self.max_properties = attributes[:'max_properties']
      end

      if attributes.key?(:'min_properties')
        self.min_properties = attributes[:'min_properties']
      end

      if attributes.key?(:'required')
        self.required = attributes[:'required']
      end

      if attributes.key?(:'additional_properties')
        self.additional_properties = attributes[:'additional_properties']
      end

      if attributes.key?(:'definitions')
        if (value = attributes[:'definitions']).is_a?(Hash)
          self.definitions = value
        end
      end

      if attributes.key?(:'properties')
        if (value = attributes[:'properties']).is_a?(Hash)
          self.properties = value
        end
      end

      if attributes.key?(:'pattern_properties')
        if (value = attributes[:'pattern_properties']).is_a?(Hash)
          self.pattern_properties = value
        end
      end

      if attributes.key?(:'dependencies')
        if (value = attributes[:'dependencies']).is_a?(Hash)
          self.dependencies = value
        end
      end

      if attributes.key?(:'enum')
        if (value = attributes[:'enum']).is_a?(Array)
          self.enum = value
        end
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'format')
        self.format = attributes[:'format']
      end

      if attributes.key?(:'all_of')
        self.all_of = attributes[:'all_of']
      end

      if attributes.key?(:'any_of')
        self.any_of = attributes[:'any_of']
      end

      if attributes.key?(:'one_of')
        self.one_of = attributes[:'one_of']
      end

      if attributes.key?(:'_not')
        self._not = attributes[:'_not']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@multiple_of.nil? && @multiple_of <= 0
        invalid_properties.push('invalid value for "multiple_of", must be greater than 0.')
      end

      if !@max_length.nil? && @max_length < 0
        invalid_properties.push('invalid value for "max_length", must be greater than or equal to 0.')
      end

      if !@max_items.nil? && @max_items < 0
        invalid_properties.push('invalid value for "max_items", must be greater than or equal to 0.')
      end

      if !@max_properties.nil? && @max_properties < 0
        invalid_properties.push('invalid value for "max_properties", must be greater than or equal to 0.')
      end

      if !@enum.nil? && @enum.length < 1
        invalid_properties.push('invalid value for "enum", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@multiple_of.nil? && @multiple_of <= 0
      return false if !@max_length.nil? && @max_length < 0
      return false if !@max_items.nil? && @max_items < 0
      return false if !@max_properties.nil? && @max_properties < 0
      return false if !@enum.nil? && @enum.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] multiple_of Value to be assigned
    def multiple_of=(multiple_of)
      if !multiple_of.nil? && multiple_of <= 0
        fail ArgumentError, 'invalid value for "multiple_of", must be greater than 0.'
      end

      @multiple_of = multiple_of
    end

    # Custom attribute writer method with validation
    # @param [Object] max_length Value to be assigned
    def max_length=(max_length)
      if !max_length.nil? && max_length < 0
        fail ArgumentError, 'invalid value for "max_length", must be greater than or equal to 0.'
      end

      @max_length = max_length
    end

    # Custom attribute writer method with validation
    # @param [Object] max_items Value to be assigned
    def max_items=(max_items)
      if !max_items.nil? && max_items < 0
        fail ArgumentError, 'invalid value for "max_items", must be greater than or equal to 0.'
      end

      @max_items = max_items
    end

    # Custom attribute writer method with validation
    # @param [Object] max_properties Value to be assigned
    def max_properties=(max_properties)
      if !max_properties.nil? && max_properties < 0
        fail ArgumentError, 'invalid value for "max_properties", must be greater than or equal to 0.'
      end

      @max_properties = max_properties
    end

    # Custom attribute writer method with validation
    # @param [Object] enum Value to be assigned
    def enum=(enum)
      if !enum.nil? && enum.length < 1
        fail ArgumentError, 'invalid value for "enum", number of items must be greater than or equal to 1.'
      end

      @enum = enum
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          schema == o.schema &&
          title == o.title &&
          description == o.description &&
          default == o.default &&
          multiple_of == o.multiple_of &&
          maximum == o.maximum &&
          exclusive_maximum == o.exclusive_maximum &&
          minimum == o.minimum &&
          exclusive_minimum == o.exclusive_minimum &&
          max_length == o.max_length &&
          min_length == o.min_length &&
          pattern == o.pattern &&
          additional_items == o.additional_items &&
          items == o.items &&
          max_items == o.max_items &&
          min_items == o.min_items &&
          unique_items == o.unique_items &&
          max_properties == o.max_properties &&
          min_properties == o.min_properties &&
          required == o.required &&
          additional_properties == o.additional_properties &&
          definitions == o.definitions &&
          properties == o.properties &&
          pattern_properties == o.pattern_properties &&
          dependencies == o.dependencies &&
          enum == o.enum &&
          type == o.type &&
          format == o.format &&
          all_of == o.all_of &&
          any_of == o.any_of &&
          one_of == o.one_of &&
          _not == o._not
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, schema, title, description, default, multiple_of, maximum, exclusive_maximum, minimum, exclusive_minimum, max_length, min_length, pattern, additional_items, items, max_items, min_items, unique_items, max_properties, min_properties, required, additional_properties, definitions, properties, pattern_properties, dependencies, enum, type, format, all_of, any_of, one_of, _not].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MockServer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
